
package entities;

import java.io.Serializable;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.MapsId;
import jakarta.persistence.OneToOne;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

@Data
//Here we rely on the id values being autogenerated!
@EqualsAndHashCode(of={"id"})
@Entity
@NoArgsConstructor
@RequiredArgsConstructor
public class ParkingLot implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    private int id;

    @NonNull
    private String location;

    @NonNull
    // Owning side of a one-to-one relationship
    @OneToOne
    // Do not add a separate join column; map the foreign key to the primary key
    @MapsId("id")
    private Employee employee;
}
