ALTER TABLE EMPLOYEE DROP CONSTRAINT EMPLOYEE_dept_id
ALTER TABLE PARKINGLOT DROP CONSTRAINT PRKINGLOTMPLOYEEID
ALTER TABLE scheduling DROP CONSTRAINT scheduling_met_id
ALTER TABLE scheduling DROP CONSTRAINT scheduling_emp_id
DROP TABLE EMPLOYEE
DROP TABLE PARKINGLOT
DROP TABLE DEPARTMENT
DROP TABLE MEETING
DROP TABLE scheduling
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
